name: transaction_viewer_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2

#  launch url
  url_launcher: ^6.1.11

#  fetch sms
  flutter_sms_inbox: ^1.0.2

#  takes permission for sms
  permission_handler: ^10.2.0

#  responsive design
  responsive_sizer: ^3.1.1

#  Format Date-Time
  intl: ^0.18.1

#  group listview
  grouped_list: ^5.1.2
  sticky_headers: ^0.3.0+2

#  page_indicator
  smooth_page_indicator: ^1.1.0

#  navigation bar
  circle_nav_bar: ^2.0.1+1

#  tab bar
  slide_switcher: ^1.1.2

#  toast message
  fluttertoast: ^8.1.2

#  share intent
  share_plus: ^6.3.1

#  api calling
  http: ^0.13.6

#  dropdown
  dropdown_button2: ^2.1.3

#  flutter webview
  flutter_inappwebview: ^5.7.2+3

#  html file data load
  html: ^0.15.3
  flutter_html: ^3.0.0-beta.2

#  sqlite data base
  sqflite: ^2.2.8+4
  path: ^1.8.2

#  Advertisement
  google_mobile_ads: ^2.3.0
  facebook_audience_network: ^1.0.1

#  firebase
  firebase_core: ^2.4.1
  firebase_remote_config: ^3.0.9


  get: 4.6.5

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter


flutter:
  assets:
    - assets/reg.json
    - assets/bank_list_icons.json
    - assets/IFSC_Code/
    - assets/splash_screen/
    - assets/Icons/
    - assets/bank icons/
    - assets/fuel_price_city/
    - assets/credit card/
    - assets/credit_card_apply.json
    - assets/schemes files/
    - assets/credit & loan files/
    - assets/bankholiday.json
    - assets/bank_numbers.json
    - assets/myDatabase.db

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Black.ttf
          weight: 900

  uses-material-design: true

